version: '3.4'
services:
  cf-audit: &auditor
    image: geometalab/conflator-cf-audit
    build: .
    environment:
      # uncomment following line to enable debugging
      # DEBUG: yes
      DATABASE_URI: 'postgresql://cf_audit:pw@database:5432/cf_audit'
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - database
  migrate:
    <<: *auditor
    command: python3 migrate.py
    ports: []
  database:
    image: postgres:10
    environment:
      POSTGRES_USER: cf_audit
      POSTGRES_PASSWORD: pw
      POSTGRES_DB: cf_audit
      ADMINS: '290271'

